# Usar a imagem oficial do PostgreSQL como imagem base
FROM postgres

# Definir as variáveis de ambiente para o usuário e senha do PostgreSQL
ENV POSTGRES_USER quiz
ENV POSTGRES_PASSWORD quiz

# Copiar o arquivo de configuração personalizado para o contêiner
COPY postgresql.conf /etc/postgresql/postgresql.conf

# Expor a porta 5432 para permitir conexões externas
EXPOSE 5432

# Copiar os arquivos SQL para inicializar o banco de dados (opcional)
COPY init.sql /docker-entrypoint-initdb.d/

# Inicializar o banco de dados PostgreSQL
CMD ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]